### ISSUE TITLE
Last release 0.8.1 on pypi requires eccodes-python which is obsolated by eccodes

### ISSUE THREAD

**Issue by thebaptiste** [ecmwf/pdbufr#19]
I have seen that this is fixed in master branch, but could you release on pypi ?
This is a problem because last release of climetlab requires eccodes and pdbufr, pdbufr requires eccodes-python, so both eccodes and eccodes-python are installed when installing climetlab, which is a bit confusing...

Thanks

**Comment by alexamici** [comment]
Released version 0.8.2, with also a significant speed boost.

Remember that this is still *alpha* code, so things may change.

**Comment by thebaptiste** [comment]
Thanks !
