### ISSUE TITLE
Can subsetNumber in uncompressed messages be considered a coordinate descriptor?

### ISSUE THREAD

**Issue by alexamici** [ecmwf/pdbufr#20]
@sandorkertesz and @shahramn

would treat `subsetNumber` like other coordinate descriptor remove the need to special case uncompressed messages?

I'm still implementing handling coordinate descriptor, but from what I see I can consolidate parsing uncompressed messages in the same code.

**Comment by shahramn** [comment]
I hadn't considered that use case. For uncompressed messages, the key iterator will return the key "subsetNumber" at the beginning of each block for a subset but its value will not reflect the actual subset number

**Comment by shahramn** [comment]
Note that you can use ecCodes own key syntax for "search by condition" using "subsetNumber" e.g.
```key="/subsetNumber=9/airTemperature"```

**Comment by alexamici** [comment]
It works perfectly.
