### ISSUE TITLE
Warning: ecCodes 2.22.0 or higher is recommended. You are running version 2.21.0

### ISSUE THREAD

**Issue by meteoDaniel** [ecmwf/pdbufr#27]
Just a short hint for you, but ecCodes 2.20.0 is not published yet. 

*Based on these [releases](https://confluence.ecmwf.int/display/ECC/Releases)

**Comment by iainrussell** [comment]
@shahramn , this comes from eccodes-python. It recommends eccodes binaries version 2.22.0 - is that a mistake perhaps?

**Comment by shahramn** [comment]
@iainrussell  in the "develop" branch of eccodes-python (v1.3.0) we recommend the develop version of the ecCodes engine i.e, 2.22.0
If you use the "master" branch of eccodes-python, then it would recommend 2.21.0

**Comment by shahramn** [comment]
I have made a new eccodes-python release. See https://pypi.org/project/eccodes/
Version 1.3.1
The warning re recommended version is fixed

**Comment by meteoDaniel** [comment]
Okay sounds like a minor issue and you were able to fix it . Great.
