### ISSUE TITLE
Allow to use comparison operators in filter conditions

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/pdbufr#9]
With this we could extract e.g. airTemperature values < 273.16.

**Comment by alexamici** [comment]
I refactored the whole filtering into `bufr_filters.py` and added support for range and slice filtering. See the tests in `test_20_bufr_filters.py` for examples.

I'll keep the issue open until I sync the README

**Comment by sandorkertesz** [comment]
Does the slicing work for datetime?
